### ISSUE TITLE
Add Sentry tracking for agent errors

### ISSUE THREAD

**Issue by nbrahms** [returntocorp/sgrep-action#199]
Right now we rely on bug reports to detect errors. Let's engineer a method to return errors to a centralized location.

Suggestion here is to use Sentry, but we could, of course, use a homebuilt or alternate solution.

One concern is how to ensure that sensitive user data are removed or obfuscated (specifically any code content).

**Comment by underyx** [comment]
We needed a sample error that should be tracked. I found a good candidate. Add this snippet to a policy via the Playground page:

```yaml
rules:
- id: error-sentinel-1234
  message: error sentinel 1234
  languages: [python]
  severity: WARNING
  pattern: 1234
```

Now run a scan with this policy, and semgrep-agent will fail because the pattern is an integer (`pattern: 1234` should instead be `pattern: "1234"`).
