### ISSUE TITLE
Generating a SARIF Report Causes Semgrep to Crash

### ISSUE THREAD

**Issue by pyth0n1c** [returntocorp/sgrep-action#376]
Hello,
Generating a report and writing to SARIF File currently causes Semgrep to crash.  There's a lot of output, so here's a link to a failed test run:
https://github.com/splunk/security_content/runs/3657205995?check_suite_focus=true
Please note that Upload SARIF File Step also fails, but that is because the file is not generated in the previous step.
The Workflow that causes this is:

```
name: Semgrep

on:
  push:
  pull_request:
    types: [opened, reopened]
jobs:     
  semgrep:
    name: Scan
    runs-on: ubuntu-latest
    steps:
      # Checkout project source
      - uses: actions/checkout@v2

      # Scan code using project's configuration on https://semgrep.dev/manage
      - uses: returntocorp/semgrep-action@v1
        with:
          generateSarif: "1"
          config: >- # more at semgrep.dev/explore
            p/security-audit
            p/secrets
      # Upload SARIF file generated in previous step
      #The following lines are commented out right now pending a fix to the semgrep repo
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: semgrep.sarif
        if: always()

```
