### ISSUE TITLE
Semgrep action failed with exit code 2

### ISSUE THREAD

**Issue by nelenkov** [returntocorp/sgrep-action#377]
We are suddenly getting scan errors on projects that worked previously.

Any ideas about the cause of this or how to debug it?

Error output is below:

```
| using semgrep rules from https://semgrep.dev/c/p/r2c-ci
| using default path ignore rules of common test and dependency directories
| found 116 files in the paths to be scanned
| skipping 3 files based on path ignore rules
=== looking for current issues in 113 files
| 8 current issues found
| No ignored issues found
=== not looking at pre-existing issues since all files with current issues are newly created
=== re-running scan to generate a SARIF report

=== failed command's STDOUT:

    {"$schema": "https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Schemata/sarif-schema-2.1.0.json", " ... "version": "2.1.0"}

=== failed command's STDERR:

Error: ROR] `/root/.local/bin/semgrep --config https://semgrep.dev/c/p/r2c-ci --debug --sarif -o /tmp/tmphopav8rz <long list of filenames in repo>
```

Workflow file is pretty typical:

```
name: Semgrep

on:
  push:
    branches: [ master ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ master ]
  schedule:
    - cron: '33 1 * * 0'

jobs:
  semgrep:
    name: Scan
    runs-on: ubuntu-latest
    steps:
      # Checkout project source
      - uses: actions/checkout@v2

      # Scan code using project's configuration on https://semgrep.dev/manage
      - uses: returntocorp/semgrep-action@v1
        with:
          config: p/r2c-ci
          generateSarif: "1"
          auditOn: push

      # Upload SARIF file generated in previous step
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: semgrep.sarif
        if: hashFiles('semgrep.sarif') != ''
```
