### ISSUE TITLE
Output as json file?

### ISSUE THREAD

**Issue by mikkeschiren** [returntocorp/sgrep-action#555]
Integrated the action in a project and it works fine.
One thing I would like to do is save the report in json (--json) to a file (--output), how do I do that?

**Comment by mikkeschiren** [comment]
Json I got sorted:
```
      env:
        SEMGREP_JSON_OUTPUT: true
```
But how do get the input in a file? I am pushing this file later to an endpoint.

**Comment by zakrush** [comment]
You can use: `--gitlab-json > report.json`

**Comment by mikkeschiren** [comment]
I got this sorted with some help on slack, like:
```
on: [pull_request]
jobs:
  semgrep:
    runs-on: ubuntu-20.04
    container:
      image: returntocorp/semgrep
    steps:
      - uses: actions/checkout@v3
      - run: semgrep ci -config p/r2c-security-audit --config p/secrets --config p/owasp-top-ten --json --output reports/semgrep.json
      ```
