### ISSUE TITLE
Cannot run `semgrep ci` while logged in and with explicit config. Use semgrep.dev to configure rules to run.

### ISSUE THREAD

**Issue by lfama** [returntocorp/sgrep-action#557]
Hi,

I've setup semgrep-agent in my GitLab and it works fine (without setting the SEMGREP_RULES variable). 
But as soon as I add the SEMGREP_RULES variable in my .gitlab-ci.yml file, the semgrep-agent step fails with the following error:
 
**Cannot run `semgrep ci` while logged in and with explicit config. Use semgrep.dev to configure rules to run.**

The only change I made in my .gitlab-ci.yml is adding the following lines:

```yaml
SEMGREP_RULES: >- 
      p/security-audit
      p/secrets
```

It seems I'm getting the same error as in #https://github.com/returntocorp/semgrep/issues/4923 but I couldn't figure out how to solve it.

Maybe I'm doing something wrong but I can't understand why I'm getting this error. Could someone give me a hint?

This is the complete .gitlab-ci.yml file I'm using:

```yaml
semgrep:
  image: returntocorp/semgrep-agent:v1
  
  script: semgrep-agent
  
  variables:
    SEMGREP_RULES: >- # more at semgrep.dev/r
      p/security-audit
      p/secrets
    SEMGREP_APP_TOKEN: $SEMGREP_APP_TOKEN
  rules:
  - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
```

Thanks!
