### ISSUE TITLE
Warning: Unexpected input(s) 'generateSarif', valid inputs are ['entryPoint', 'args', 'config', 'publishToken']

### ISSUE THREAD

**Issue by HariSekhon** [returntocorp/sgrep-action#573]
I have semgrep-action using sarif uploads to GitHub Security which used to work but recently started having this warning:

```
Warning: Unexpected input(s) 'generateSarif', valid inputs are ['entryPoint', 'args', 'config', 'publishToken']

...

=========== DEPRECATION WARNING ===========

Semgrep's SARIF file generation is changing by 2022 May.
Please update your CI configuration. Your CI script should run this command to get a SARIF file:
    $ semgrep scan --sarif --output=semgrep.sarif
```

Although it did still find and upload the sarif file to GitHub Security.

After I commented out the deprecated `generateSarif` line which was supposed ignored with a warning above:

```
      - uses: returntocorp/semgrep-action@v1
        with:
          #generateSarif: "1"
          config: ...
```

it then started failing to find the sarif file to upload:

```
Run github/codeql-action/upload-sarif@v1
Error: Path does not exist: semgrep.sarif
```

It's not clear from the docs how to re-enable sarif generation.

I've checked:

https://semgrep.dev/docs/semgrep-ci/overview/
https://semgrep.dev/docs/semgrep-ci/configuration-reference/
https://semgrep.dev/docs/semgrep-ci/sample-ci-configs/#github-actions

but none of these pages even contains the word 'sarif'.

I can see the CLI it's supposed to use `--output=semgrep.sarif` now but it's not clear how to get the action to do this from the current docs, which I think need updating?

**Comment by brendongo** [comment]
Hi! You will want to change your configuration to something like:

```
name: Semgrep

on:
  # Scan all files on branches, block on any issues
  push:
    branches: ["master", "main"]
    
jobs:
  semgrep:
    name: Scan
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    # Skip any PR created by dependabot to avoid permission issues
    if: (github.actor != 'dependabot[bot]')
    steps:
      # Fetch project source
      - uses: actions/checkout@v3

      - run: semgrep ci --sarif --output=semgrep.sarif
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
      <INSERT YOUR OTHER STEPS THAT USE THE SARIF FILE>

```

**Comment by brendongo** [comment]
note it is actually changing from using the semgrep-action to using just semgrep

**Comment by HariSekhon** [comment]
So is the semgrep-action broken or deprecated?

Also, what is the equivalent to the github action's config, as the the `semgrep --help` seems to indicate that `--config` is yaml rather than this:

```
     - uses: returntocorp/semgrep-action@v1
        with:
          config: >-
            p/security-audit
            p/secrets
            p/semgrep-misconfigurations
            p/semgrep-rule-lints
            p/github-actions
            p/ci
            p/owasp-top-ten
            p/command-injection
            p/sql-injection
```

**Comment by brendongo** [comment]
It is still maintained but only for the most simple use case and we offload any special casing like sarif output to main semgrep.

You can run this with `semgrep ci --config p/security-audit --config p/secrets --config ...`

**Comment by HariSekhon** [comment]
That's a shame... I'd say sarif is a core use case supported by most code scanning tools I've seen, especially for anything relating to use of GitHub which is basically everything these days. I would have expected it to remain supported by the semgrep action.

**Comment by brendongo** [comment]
@HariSekhon it is still supported by semgrep and you can configure semgrep to run in github actions using the configuration in https://github.com/returntocorp/semgrep-action/issues/573#issuecomment-1125445113

All the functionality that was in semgrep-action was absorbed into semgrep

**Comment by mdantonio** [comment]
Hello,
I changed my workflow as suggested (replaced the action with `semgrep ci --sarif --output=semgrep.sarif`) and now the scan is working, but the upload step is still failing:

```
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: semgrep.sarif
        if: always()
```

=>

```
Error: Unable to upload "semgrep.sarif" as it is not valid SARIF:
- instance additionalProperty "fixes" exists in instance when not allowed
Error: Unable to upload "semgrep.sarif" as it is not valid SARIF:
- instance additionalProperty "fixes" exists in instance when not allowed
    at validateSarifFileSchema (/__w/_actions/github/codeql-action/v2/lib/upload-lib.js:203:15)
    at uploadFiles (/__w/_actions/github/codeql-action/v2/lib/upload-lib.js:267:9)
    at Object.uploadFromActions (/__w/_actions/github/codeql-action/v2/lib/upload-lib.js:139:18)
    at async run (/__w/_actions/github/codeql-action/v2/lib/upload-sarif-action.js:52:30)
    at async runWrapper (/__w/_actions/github/codeql-action/v2/lib/upload-sarif-action.js:74:9)
```

Could you help me restore the workflow? :pray:
