### ISSUE TITLE
Add exclude option in the Semgrep action yml file

### ISSUE THREAD

**Issue by matthernet** [returntocorp/sgrep-action#660]
**Is your feature request related to a problem? Please describe**
Hi, I want to use a specific ruleset but also I would need to exclude one particular rule since I'm working on some test, I know that the option was added [HERE](https://semgrep.dev/docs/release-notes/september-2022/#semgrep-cli) for the CLI, but there is an option for the docker in GH actions?

**Describe the solution you'd like**
For example something like these where you are able to add the name (or names separated by , ) and Semgrep will use all the rules from the ruleset except the ones detailed 
```
jobs:
  semgrep:
    name: Semgrep Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: returntocorp/semgrep-action@v1
        with:
          config:
            p/owasp-top-ten --exclude csharp.dotnet.security.audit.missing-or-broken-authorization.missing-or-broken-authorization
```
